services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: hidden_village
      POSTGRES_PASSWORD: hidden_village
      POSTGRES_DB: hidden_village
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    ports:
      - '6379:6379'

volumes:
  postgres-data:
