/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedTransactionsRouteImport } from './routes/_protected/transactions'
import { Route as ProtectedTrackerRouteImport } from './routes/_protected/tracker'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedJobsRouteImport } from './routes/_protected/jobs'
import { Route as ProtectedInboxRouteImport } from './routes/_protected/inbox'
import { Route as ProtectedExportsRouteImport } from './routes/_protected/exports'
import { Route as ApiGmailConnectRouteImport } from './routes/api/gmail/connect'
import { Route as ApiGmailCallbackRouteImport } from './routes/api/gmail/callback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBankingEnableBankingCallbackRouteImport } from './routes/api/banking/enable-banking/callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTransactionsRoute = ProtectedTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTrackerRoute = ProtectedTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedJobsRoute = ProtectedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInboxRoute = ProtectedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedExportsRoute = ProtectedExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiGmailConnectRoute = ApiGmailConnectRouteImport.update({
  id: '/api/gmail/connect',
  path: '/api/gmail/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailCallbackRoute = ApiGmailCallbackRouteImport.update({
  id: '/api/gmail/callback',
  path: '/api/gmail/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBankingEnableBankingCallbackRoute =
  ApiBankingEnableBankingCallbackRouteImport.update({
    id: '/api/banking/enable-banking/callback',
    path: '/api/banking/enable-banking/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/exports': typeof ProtectedExportsRoute
  '/inbox': typeof ProtectedInboxRoute
  '/jobs': typeof ProtectedJobsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/tracker': typeof ProtectedTrackerRoute
  '/transactions': typeof ProtectedTransactionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/gmail/callback': typeof ApiGmailCallbackRoute
  '/api/gmail/connect': typeof ApiGmailConnectRoute
  '/api/banking/enable-banking/callback': typeof ApiBankingEnableBankingCallbackRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/exports': typeof ProtectedExportsRoute
  '/inbox': typeof ProtectedInboxRoute
  '/jobs': typeof ProtectedJobsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/tracker': typeof ProtectedTrackerRoute
  '/transactions': typeof ProtectedTransactionsRoute
  '/': typeof ProtectedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/gmail/callback': typeof ApiGmailCallbackRoute
  '/api/gmail/connect': typeof ApiGmailConnectRoute
  '/api/banking/enable-banking/callback': typeof ApiBankingEnableBankingCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/exports': typeof ProtectedExportsRoute
  '/_protected/inbox': typeof ProtectedInboxRoute
  '/_protected/jobs': typeof ProtectedJobsRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/tracker': typeof ProtectedTrackerRoute
  '/_protected/transactions': typeof ProtectedTransactionsRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/gmail/callback': typeof ApiGmailCallbackRoute
  '/api/gmail/connect': typeof ApiGmailConnectRoute
  '/api/banking/enable-banking/callback': typeof ApiBankingEnableBankingCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/exports'
    | '/inbox'
    | '/jobs'
    | '/settings'
    | '/tracker'
    | '/transactions'
    | '/api/auth/$'
    | '/api/gmail/callback'
    | '/api/gmail/connect'
    | '/api/banking/enable-banking/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/exports'
    | '/inbox'
    | '/jobs'
    | '/settings'
    | '/tracker'
    | '/transactions'
    | '/'
    | '/api/auth/$'
    | '/api/gmail/callback'
    | '/api/gmail/connect'
    | '/api/banking/enable-banking/callback'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/_protected/exports'
    | '/_protected/inbox'
    | '/_protected/jobs'
    | '/_protected/settings'
    | '/_protected/tracker'
    | '/_protected/transactions'
    | '/_protected/'
    | '/api/auth/$'
    | '/api/gmail/callback'
    | '/api/gmail/connect'
    | '/api/banking/enable-banking/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGmailCallbackRoute: typeof ApiGmailCallbackRoute
  ApiGmailConnectRoute: typeof ApiGmailConnectRoute
  ApiBankingEnableBankingCallbackRoute: typeof ApiBankingEnableBankingCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/transactions': {
      id: '/_protected/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof ProtectedTransactionsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tracker': {
      id: '/_protected/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof ProtectedTrackerRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/jobs': {
      id: '/_protected/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof ProtectedJobsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inbox': {
      id: '/_protected/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof ProtectedInboxRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/exports': {
      id: '/_protected/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ProtectedExportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/gmail/connect': {
      id: '/api/gmail/connect'
      path: '/api/gmail/connect'
      fullPath: '/api/gmail/connect'
      preLoaderRoute: typeof ApiGmailConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail/callback': {
      id: '/api/gmail/callback'
      path: '/api/gmail/callback'
      fullPath: '/api/gmail/callback'
      preLoaderRoute: typeof ApiGmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/banking/enable-banking/callback': {
      id: '/api/banking/enable-banking/callback'
      path: '/api/banking/enable-banking/callback'
      fullPath: '/api/banking/enable-banking/callback'
      preLoaderRoute: typeof ApiBankingEnableBankingCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedExportsRoute: typeof ProtectedExportsRoute
  ProtectedInboxRoute: typeof ProtectedInboxRoute
  ProtectedJobsRoute: typeof ProtectedJobsRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedTrackerRoute: typeof ProtectedTrackerRoute
  ProtectedTransactionsRoute: typeof ProtectedTransactionsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedExportsRoute: ProtectedExportsRoute,
  ProtectedInboxRoute: ProtectedInboxRoute,
  ProtectedJobsRoute: ProtectedJobsRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedTrackerRoute: ProtectedTrackerRoute,
  ProtectedTransactionsRoute: ProtectedTransactionsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGmailCallbackRoute: ApiGmailCallbackRoute,
  ApiGmailConnectRoute: ApiGmailConnectRoute,
  ApiBankingEnableBankingCallbackRoute: ApiBankingEnableBankingCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
