import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useQueryClient } from "@tanstack/react-query";
import { AlertCircle, Clock, Timer } from "lucide-react";
import { EmptyState } from "@/components/shared/empty-state";
import { RelativeTime } from "@/components/shared/relative-time";
import { SortableHeader, useSort } from "@/components/shared/sortable-header";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useDelayedSchedulers, useRefresh, useRepeatableSchedulers, } from "@/lib/hooks";
import { formatDuration } from "@/lib/utils";
export function SchedulersPage({ search, onSearchChange, }) {
    const _queryClient = useQueryClient();
    // Sort hooks
    const { currentSort: repeatableSort, handleSort: handleRepeatableSort } = useSort(search.repeatableSort, (sort) => onSearchChange({ ...search, repeatableSort: sort }));
    const { currentSort: delayedSort, handleSort: handleDelayedSort } = useSort(search.delayedSort, (sort) => onSearchChange({ ...search, delayedSort: sort }));
    const { data: repeatable = [], isLoading: repeatableLoading, error: repeatableError, isRefetching: repeatableRefetching, } = useRepeatableSchedulers(search.repeatableSort);
    const { data: delayed = [], isLoading: delayedLoading, error: delayedError, isRefetching: delayedRefetching, } = useDelayedSchedulers(search.delayedSort);
    // Server-side cache refresh
    const refreshMutation = useRefresh();
    const _loading = repeatableLoading ||
        delayedLoading ||
        repeatableRefetching ||
        delayedRefetching ||
        refreshMutation.isPending;
    const error = repeatableError || delayedError;
    const _refresh = () => {
        refreshMutation.mutate();
    };
    if (repeatableLoading || delayedLoading) {
        return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("div", { className: "h-7 w-32 animate-pulse rounded bg-muted" }), _jsx("div", { className: "h-9 w-9 animate-pulse rounded bg-muted" })] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex gap-2", children: [_jsx("div", { className: "h-9 w-32 animate-pulse rounded bg-muted" }), _jsx("div", { className: "h-9 w-28 animate-pulse rounded bg-muted" })] }), _jsxs("div", { className: "grid grid-cols-12 gap-4 border-b border-dashed py-2.5 text-[11px] uppercase tracking-wider text-muted-foreground", children: [_jsx("div", { className: "col-span-3", children: "Name" }), _jsx("div", { className: "col-span-2", children: "Queue" }), _jsx("div", { className: "col-span-3", children: "Pattern" }), _jsx("div", { className: "col-span-2", children: "Next Run" }), _jsx("div", { className: "col-span-2", children: "Timezone" })] }), _jsx("div", { className: "divide-y divide-border/50", children: [...Array(10)].map((_, i) => (_jsxs("div", { className: "grid grid-cols-12 items-center gap-4 py-3", children: [_jsxs("div", { className: "col-span-3 flex items-center gap-2", children: [_jsx("div", { className: "h-4 w-4 animate-pulse rounded bg-muted" }), _jsx("div", { className: "h-4 w-24 animate-pulse rounded bg-muted" })] }), _jsx("div", { className: "col-span-2", children: _jsx("div", { className: "h-3 w-16 animate-pulse rounded bg-muted" }) }), _jsx("div", { className: "col-span-3", children: _jsx("div", { className: "h-4 w-20 animate-pulse rounded bg-muted" }) }), _jsx("div", { className: "col-span-2", children: _jsx("div", { className: "h-4 w-24 animate-pulse rounded bg-muted" }) }), _jsx("div", { className: "col-span-2", children: _jsx("div", { className: "h-3 w-16 animate-pulse rounded bg-muted" }) })] }, `pulse-${i.toString()}`))) })] })] }));
    }
    if (error) {
        return (_jsx(EmptyState, { icon: AlertCircle, title: "Failed to load schedulers", description: error.message }));
    }
    return (_jsx("div", { className: "space-y-6", children: _jsxs(Tabs, { value: search.tab || "repeatable", onValueChange: (tab) => onSearchChange({ ...search, tab: tab }), children: [_jsxs(TabsList, { children: [_jsxs(TabsTrigger, { value: "repeatable", children: ["Repeatable (", repeatable.length, ")"] }), _jsxs(TabsTrigger, { value: "delayed", children: ["Delayed (", delayed.length, ")"] })] }), _jsx(TabsContent, { value: "repeatable", className: "mt-4", children: repeatable.length === 0 ? (_jsx(EmptyState, { icon: Clock, title: "No repeatable jobs", description: "No cron or repeating jobs are configured" })) : (_jsxs("div", { className: "divide-y divide-border/50", children: [_jsxs("div", { className: "grid grid-cols-12 gap-4 border-b border-dashed py-2.5 text-[11px] uppercase tracking-wider text-muted-foreground", children: [_jsx("div", { className: "col-span-3", children: _jsx(SortableHeader, { field: "name", label: "Name", currentSort: repeatableSort, onSort: handleRepeatableSort }) }), _jsx("div", { className: "col-span-2", children: _jsx(SortableHeader, { field: "queueName", label: "Queue", currentSort: repeatableSort, onSort: handleRepeatableSort }) }), _jsx("div", { className: "col-span-3", children: _jsx(SortableHeader, { field: "pattern", label: "Pattern", currentSort: repeatableSort, onSort: handleRepeatableSort }) }), _jsx("div", { className: "col-span-2", children: _jsx(SortableHeader, { field: "next", label: "Next Run", currentSort: repeatableSort, onSort: handleRepeatableSort }) }), _jsx("div", { className: "col-span-2", children: _jsx(SortableHeader, { field: "tz", label: "Timezone", currentSort: repeatableSort, onSort: handleRepeatableSort }) })] }), repeatable.map((scheduler) => (_jsxs("div", { className: "grid grid-cols-12 items-center gap-4 py-3 text-sm", children: [_jsxs("div", { className: "col-span-3 flex items-center gap-2", children: [_jsx(Clock, { className: "h-4 w-4 shrink-0 text-muted-foreground" }), _jsx("span", { className: "truncate font-medium", children: scheduler.name })] }), _jsx("div", { className: "col-span-2 truncate font-mono text-xs text-muted-foreground", children: scheduler.queueName }), _jsx("div", { className: "col-span-3 font-mono text-xs", children: scheduler.pattern ||
                                            (scheduler.every
                                                ? `every ${formatDuration(scheduler.every)}`
                                                : "-") }), _jsx("div", { className: "col-span-2 text-muted-foreground", children: scheduler.next ? (_jsx(RelativeTime, { timestamp: scheduler.next })) : ("-") }), _jsx("div", { className: "col-span-2 text-xs text-muted-foreground", children: scheduler.tz || "UTC" })] }, scheduler.key)))] })) }), _jsx(TabsContent, { value: "delayed", className: "mt-4", children: delayed.length === 0 ? (_jsx(EmptyState, { icon: Timer, title: "No delayed jobs", description: "No jobs are scheduled for future execution" })) : (_jsxs("div", { className: "divide-y divide-border/50", children: [_jsxs("div", { className: "grid grid-cols-12 gap-4 border-b border-dashed py-2.5 text-[11px] uppercase tracking-wider text-muted-foreground", children: [_jsx("div", { className: "col-span-3", children: _jsx(SortableHeader, { field: "name", label: "Name", currentSort: delayedSort, onSort: handleDelayedSort }) }), _jsx("div", { className: "col-span-2", children: _jsx(SortableHeader, { field: "queueName", label: "Queue", currentSort: delayedSort, onSort: handleDelayedSort }) }), _jsx("div", { className: "col-span-2", children: "Job ID" }), _jsx("div", { className: "col-span-3", children: _jsx(SortableHeader, { field: "processAt", label: "Executes At", currentSort: delayedSort, onSort: handleDelayedSort }) }), _jsx("div", { className: "col-span-2", children: _jsx(SortableHeader, { field: "delay", label: "Delay", currentSort: delayedSort, onSort: handleDelayedSort }) })] }), delayed.map((job) => (_jsxs("div", { className: "grid grid-cols-12 items-center gap-4 py-3 text-sm", children: [_jsxs("div", { className: "col-span-3 flex items-center gap-2", children: [_jsx(Timer, { className: "h-4 w-4 shrink-0 text-muted-foreground" }), _jsx("span", { className: "truncate font-medium", children: job.name })] }), _jsx("div", { className: "col-span-2 truncate font-mono text-xs text-muted-foreground", children: job.queueName }), _jsx("div", { className: "col-span-2 truncate font-mono text-xs text-muted-foreground", children: job.id }), _jsx("div", { className: "col-span-3 text-muted-foreground", children: _jsx(RelativeTime, { timestamp: job.processAt }) }), _jsx("div", { className: "col-span-2 text-muted-foreground", children: formatDuration(job.delay) })] }, `${job.queueName}-${job.id}`)))] })) })] }) }));
}
